import React from 'react'
import styles from "./msa.module.css"

export const metadata = {
  title: "Growmax MSA | Master Service Agreement for Platform Usage",
  description: "Review the Growmax Master Service Agreement (MSA) outlining the terms, conditions, and responsibilities related to your use of the Growmax B2B commerce platform. Understand your rights and obligations as a partner.",
  openGraph: {
    title: "Growmax MSA | Master Service Agreement for Platform Usage",
    description: "Review the Growmax Master Service Agreement (MSA) outlining the terms, conditions, and responsibilities related to your use of the Growmax B2B commerce platform. Understand your rights and obligations as a partner.",
    url: "https://www.growmax.io/msa",
    siteName: "Growmax",
    images: [
      {
        url: "https://www.growmax.io/images/HomePageImg/growmax_logo.png",
        width: 1200,
        height: 630,
        alt: "Review the Growmax Master Service Agreement (MSA) outlining the terms, conditions, and responsibilities related to your use of the Growmax B2B commerce platform. Understand your rights and obligations as a partner.",
      },
    ],
    type: "website", // or "article" for blog posts
  },
  twitter: {
    card: "summary_large_image",
    title: "Growmax MSA | Master Service Agreement for Platform Usage",
    description: "Review the Growmax Master Service Agreement (MSA) outlining the terms, conditions, and responsibilities related to your use of the Growmax B2B commerce platform. Understand your rights and obligations as a partner.",
    images: ["https://www.growmax.io/images/HomePageImg/growmax_logo.png"],
    site: "@growmax_io",
  },
};


const MSA = () => {
  return (
    <div className={styles.legalContainer}>
        <h3 className={styles.legalHeading}>MASTER SAAS SUBSCRIPTION AGREEMENT</h3>
        <p className={styles.legalPassage}>Last updated: December 01, 2020<br/><br/><br/>This Master SaaS Subscription Agreement (“Agreement”) is entered into by and between Apptino Software Private Limited (“Apptino”) and the customer specified in the Order Form (“Customer”) and is effective as of the date specified in the Order Form (the “Effective Date”).<br/>This Agreement permits Customer to subscribe for Growmax &ndash; B2B eCommerce offered as software-as-a-service hereto (the “Service”) pursuant to Apptino order forms referencing this Agreement (“Order Form(s)”) and sets forth the basic terms and conditions under which those Service will be delivered. This Agreement shall govern Customer&apos;s initial subscription on the order form effective date as well as any future subscriptions made by Customer which reference this Agreement.<br/>These Terms and Conditions (“Terms”, “Terms & Conditions”) governs the relationship between the Parties with respect to the SaaS based B2B eCommerce https://”domain”.growmax.io or https://”domain”.myapptino.com or https://”domain”.bcommerce.in website (the “Service”) operated by Apptino.<br/>Please read these terms and conditions carefully before using the Service.<br/>Your access to and use of the Service is conditioned on your acceptance of and compliance with these Terms and Conditions. These Terms and Conditions apply to all visitors, users and others who access or use the Service.<br/>By accessing or using the Service you agree to be bound by these Terms. If you disagree with any part of the terms then you may not access the Service.</p>
        <h3 className={styles.legalHeading}>1. MODIFICATIONS TO THIS AGREEMENT</h3>
        <p className={styles.legalPassage}>1.1 Apptino reserves the right to revise this Agreement from time to time. Apptino will date and post the updated version of this Agreement on the Apptino website located at www.apptino.com/legal & www.growmax.io/msa. Any changes will be effective upon posting the updated version of the Agreement (or such later effective date as may be indicated at the bottom of the updated Agreement). Customer&apos;s continued access or use of any portion of the Service constitutes Customer&apos;s acceptance of such changes. If Customer does not agree to any of the changes, Customer must cease use of the Service and inform Apptino immediately at support@growmax.io.</p>
        <h3 className={styles.legalHeading}>2. SAAS SERVICES AND SUPPORT</h3>
        <p className={styles.legalPassage}>2.1 During the Subscription period, Apptino provides to customer, directly or through its subcontractors or its licensors, a non-exclusive, non-transferable, non-sub licensable, non-assignable, royalty-free license with a nationwide (India) right to access and use the Service solely for Customer&apos;s internal business operations subject to the terms of this Agreement and up to the number of users documented in the Schedule 1 of the Order Form.
        <br/><br/>
        2.2 Company acknowledges that this Agreement is a SaaS agreement and Apptino will not be delivering copies of the Software to Customer as part of the Service.
        <br/><br/>
        2.3 Apptino may utilize its subcontractors or its licensors in the provision of such Service so long as such subcontractors or licensors are bound to contractual terms no less protective of Customer&apos;s rights provided hereunder and provided further that any use of subcontractors or licensors in the operation of any applicable service is subject to the same security controls and audits as if performed by Apptino employees.
        <br/><br/>
        2.4 Customer acknowledges and agrees that in order for Customer to access and use SaaS Services, Customer is required to maintain minimum requirements (such as operating system versions, browsers etc.) as stated in the Documentation. If required, information about updates to minimum requirements will be provided to Customer during the Subscription period.</p>
        <h3 className={styles.legalHeading}>3. USE OF SERVICES AND CONTENT</h3>
        <p className={styles.legalPassage}>3.1 Subscriptions Unless otherwise provided in the applicable Order Form, (a) Service and access to Content are ordered on Subscription basis for a set period designated on the applicable Order Form (each, a Subscription Period), (b) Subscription for ordered Service may be added during a subscription period at the same pricing as the underlying subscription pricing, prorated for the portion of that subscription period remaining at the time the subscriptions are added, (c) Service that will be made available to Customer will be set forth in one or more Order Forms executed by the Parties from time to time during the Subscription period, (d) Apptino may also offer training and API support services (“Professional Services”) related to the Service. Customer will order and Apptino will provide the Service and related Professional Services (if any) as specified in the applicable Order Form, and (e) Each Order Form shall set out a description of the applicable Service to be provided by Apptino and the costs associated with it. Each Order Form shall be incorporated in this Agreement by reference.<br/><br/>
        3.2 Provision of Access Subject to the terms and conditions contained in this Agreement, Apptino hereby grants to Customer and its Authorized Users a non-exclusive, non-transferable right to access the features and functions of the applicable Service set forth in the applicable Order Form during the Period for the number of Authorized Users up to the Service Limits. On or as soon as reasonably practicable after the Effective Date, Apptino shall provide to Customer the necessary URL / Login credentials to allow Customer and its Authorized Users to access the Service. Customer and its Authorized Users may access and use the Service and access to the same are permitted only by the number of Authorized Users of Customer specified in the applicable Order Form. If Customer is given passwords to access the Service, Customer shall require that all Authorized Users keep user ID and password information strictly confidential and not share such information with any unauthorized person. User IDs are granted to an individual, named persons and may not be shared. Customer and any Authorized User may only use the Service in accordance with the Access Protocols solely for its own benefit and in accordance with the terms and conditions of this Agreement, the end user technical documentation provided with the Service and any data usage or other scopes of use restrictions designated in the applicable Order Form. Customer shall be responsible for any and all actions are taken using Customer&apos;s accounts and passwords, and shall immediately delete if any Authorized User who has access to a user ID is no longer an employee of Customer.<br/><br/>
        3.3 Usage Limits Service and Content are subject to usage limits, including, for example, the no. of Authorized Users specified in Order Forms and Documentation. Unless otherwise specified, (a) the Service or Content may not be accessed by more than that number of Authorized Users, (b) a User&apos;s password may not be shared with any other individual, and (c) except as set forth in an Order Form, a User identification may only be reassigned to a new individual replacing one who will no longer use the Service or Content. If the customer exceeds a contractual usage limit, Apptino may work with Customer to seek to reduce Customer&apos;s usage so that it conforms to that limit. If notwithstanding Apptino&apos;s efforts, Customer is unwilling to abide by a contractual usage limit, Customer will execute an Order Form for additional quantities of the applicable Service or Content promptly upon Apptino&apos;s request, and/or pay any invoice for excess usage in accordance with Schedule 1 of the Order Form.
        <br/><br/>
        3.4 Removal of Content and Non-Apptino Applications If Apptino is required by a licensor to remove Content, or receive information that Content provided by Customer may violate applicable law or third-party rights, Apptino may so notify Customer and in such event, Customer will promptly remove such Content from Service. If Apptino receives information that a Non-Apptino Application hosted on a Service by Customer may violate Apptino Acceptable Use or applicable law or third-party rights, Apptino may so notify Customer and in such event, Customer will promptly disable such Non-Apptino Application or modify the Non-Apptino Application to resolve the potential violation. If Customer does not take required action in accordance with the above, Apptino may disable the applicable Content, Service and/or Non-Apptino Application until the potential violation is resolved.
        <br/><br/>
        3.5 Contractors and Affiliates Customer may permit its independent contractors and consultants who are not competitors of Apptino (“Contractors”) to serve as Authorized Users, provided Customer remains responsible for compliance by each such independent Contractor with all of the terms and conditions of this Agreement and any such use of the Apptino SaaS by such independent Contractor or consultants is for the sole benefit of Customer. Use of the Service by independent Contractors and Customer in the aggregate must be within the restrictions specified in the applicable Order Form.
        <br/><br/>
        3.6 Unpaid Subscriptions Customer&apos;s right to access and use the Service under any Unpaid Subscription may be subject to additional limitations and restrictions as determined by Apptino in its sole discretion (e.g., limits on data usage or restrictions on product features). Apptino has the right to terminate any Unpaid Subscription at any time for any reason. NOTWITHSTANDING ANYTHING TO THE CONTRARY IN THIS AGREEMENT, Apptino WILL HAVE NO WARRANTY, SERVICE LEVEL, INDEMNITY, OR SUPPORT OBLIGATIONS WITH RESPECT TO UNPAID SUBSCRIPTIONS. If Customer wishes to use the Service beyond the trial period, then Customer must pay applicable fees to upgrade to a paid Subscription and all of the terms and conditions in this Agreement will apply to such order and to Customer&apos;s use of the Service. In the event Customer does not upgrade to a paid Subscription following the trial period, Customer acknowledges that it shall have no further access to the Customer Data input into the Service and that Apptino may delete any such data as may have been stored by Service at the time.
        </p>
        <h3 className={styles.legalHeading}>4.CUSTOMER DATA</h3>
        <p className={styles.legalPassage}>4.1 Definition Customer Data means any business information or other data of any type that is input by or on behalf of Customer into the Service and any data sets Customer creates using the Service.
        <br/><br/>
        4.2 Ownership and Use of Customer Data Customer retains all right, title and interest (including any and all intellectual property rights) in and to the Customer Data, and Apptino acknowledges that it neither owns nor acquires any additional rights in and to the Customer Data not expressly granted by this Agreement. Apptino further acknowledges that Customer retains the right to use the Customer Data for any purpose in Customer&apos;s sole discretion. Subject to the foregoing, Customer hereby grants to Apptino a non-exclusive, worldwide, royalty-free, non-transferable right and license to use, copy, store, transmit, modify, create derivative works of and display the Customer Data during the Period for the limited purposes of performing Apptino&apos;s obligations under this Agreement. Customer further grants Apptino the right to create anonymous profiles and derivative insights based on the Customer Data that it may use as part of the Service for Customer and other customers of Apptino; provided, however, that such Insights do not disclose any Customer Confidential Information or otherwise disclose the identity of Customer.
        <br/><br/>
        4.3 Storage of Customer Data Apptino does not provide an archiving service. Apptino agrees only that it shall not intentionally delete any Customer Data from the Service prior to expiration/termination of Customer&apos;s applicable Subscription Term. Apptino expressly disclaims all other obligations with respect to storage.
        <br/><br/>
        4.4 Customer Obligations
        (a) In General Customer shall ensure that Customer&apos;s use of the Service and all Customer Data is at all times compliant with Customer&apos;s privacy policies and all applicable local, state, national and international laws, regulations and conventions, including, without limitation, those related to data privacy and data transfer, international communications, and the exportation of technical or personal data. Customer is solely responsible for the accuracy, content, and legality of all Customer Data. Customer represents and warrants to Apptino that Customer has sufficient rights in the Customer Data to grant the rights granted to Apptino and that the Customer Data does not infringe or violate the intellectual property, publicity, privacy or other rights of any third party,
        <br/><br/>
        (b) No Sensitive Personal Information Allowed In addition, Customer specifically agrees not to use the Apptino SaaS to store, process or transmit any Sensitive Personal Information. “Sensitive Personal Information” means any of the following: (i) credit, debit or other payment card data subject to the Payment Card Industry Data Security Standards (“PCI DSS”); (ii) patient, medical or other protected health information regulated by the Health Insurance Portability and Accountability Act (“HIPAA”); or (iii) any other information deemed to be “personal data” of an EU citizen (as such term is defined in EU Data Protection Directive 95/46/EC). Customer acknowledges that Apptino is not a Business Associate or subcontractor (as those terms are defined in HIPAA) or a payment card processor and that the Apptino SaaS is neither HIPAA nor PCI DSS compliant. Apptino shall have no liability under this Agreement for Sensitive Personal Information, notwithstanding anything to the contrary herein.
        </p>
        <h3 className={styles.legalHeading}>5.CUSTOMER RESPONSIBILITIES</h3>
        <p className={styles.legalPassage}>5.1 Authorized Users Access to Service Customer may permit any Authorized Users to access and use the features and functions of the Service as contemplated by this Agreement. Customer will be responsible for all actions or omissions of its Authorized Users. Authorized User IDs cannot be shared or used by more than one Authorized User at a time. Customer shall use commercially reasonable efforts to prevent unauthorized access to, or use of, the Service, and notify Apptino promptly of any such unauthorized use known to Customer. Customer acknowledges and agrees that it may need certain networking capabilities, bandwidth, and hardware to use the Service. Customer is solely responsible for all hardware, software, and bandwidth required to reach and access Service.
        <br/><br/>
        5.2 Assistance Customer shall provide commercially reasonable information and assistance to Apptino to enable Apptino to deliver the Service. Upon request from Apptino, Customer shall promptly deliver Customer Content, if any to Apptino in an electronic file format specified and accessible by Apptino. Customer acknowledges that Apptino&apos;s ability to deliver the Service in the manner provided in this SaaS Agreement may depend upon the accuracy and timeliness of such information and assistance.<br/><br/>
        5.3 Customer is responsible for all activities that occur in, or are related to, user accounts including the data, information stored or transmitted when accessing Service. All applications residing within Customer environment or installed on third party service providers on behalf of Customer that integrate to Service shall be managed and supported by Customer. Customer is also responsible for managing components that are downloaded onto their environment such as web browser based software plug-ins that extend Service.
        <br/><br/>
        5.4 As Customer may integrate or utilize third party links to other software, hardware or other services which are associated with, or otherwise available through the Service, Customer agrees that it&apos;s Authorized Users and anyone acting on their behalf shall use such third party links at their sole discretion. Apptino shall have no responsibility or liability with respect to such third party links used by Customer&apos;s Authorized Users for any act or omission of any such third party provider.
        <br/><br/>
        5.5 Customer and all its Authorized Users shall use the Service solely for its internal purposes as contemplated by this Agreement and shall not: (i) make Service available to any third party not authorized or as otherwise contemplated by this Agreement; (ii) send or store code that can harm or result in damage to Service (including but not limited to malicious code and malware); (iii) wilfully interfere with or disrupt the integrity of Service or the data contained therein; (iv) attempt to gain unauthorized access to the Service or its related system or networks; (v) use Service to provide services to third Parties except as expressly permitted by this Agreement; or (vi) use Services in order to cause harm such as overload or create multiple agents for the purpose of disrupting operations of a third party. A breach by the Customer of its obligations under this section shall be considered a material breach of the Agreement.
        <br/><br/>
        5.6 Compliance with Laws Customer shall comply with all applicable local, state, national and international laws in connection with its use of the Service, including those laws related to data privacy, international communications, and the transmission of technical or personal data. Customer acknowledges that Apptino exercises no control over the content of the information transmitted by Customer through the Service. Customer shall not upload, post, reproduce or distribute any information, software or other material protected by copyright, privacy rights, or any other intellectual property right without first obtaining the permission of the owner of such rights.
        <br/><br/>
        5.7 Unauthorized Use / False Information Customer shall: (a) notify Apptino immediately of any unauthorized use of any password or user id or any other known or suspected breach of security, (b) report to Apptino immediately and use reasonable efforts to stop any unauthorized use of the Service that is known or suspected by Customer, and (c) not provide false identity information to gain access to or use the Service.
        <br/><br/>
        5.8 Administrator Access Customer shall be solely responsible for the acts and omissions of its Owner / Administrator Users. Apptino shall not be liable for any loss of data or functionality caused directly or indirectly by the Owner / Administrator Users.
        <br/><br/>
        5.9 Customer Input Customer is solely responsible for collecting, inputting and updating all Customer Content stored on the Host, and for ensuring that the Customer Content does not (i) include anything that actually or potentially infringes or misappropriates the copyright, trade secret, trademark or other intellectual property right of any third party, or (ii) contain anything that is obscene, defamatory, harassing, offensive or malicious.
        <br/><br/>
        5.10 Collection of Company Data Company shall be responsible for obtaining any and all consents necessary to allow for the collection of Company Data under this Agreement and the processing of the Company Data by Apptino Customer hereby represents and warrants that the collection and transmission of the Customer Data to Apptino as contemplated by this Agreement as well as the processing of such Customer Data in conformance with the terms of this Agreement complies in all respects with all applicable laws, rules and regulations that apply to the Customer and its employees.
        <br/><br/>
        5.11. Although Apptino has no obligation to monitor Company&apos;s use of the Services, Apptino may do so and may prohibit any use of the Service it believes may be (or alleged to be) in violation of the foregoing.
        <br/><br/>
        5.12 Company shall be responsible for obtaining and maintaining any equipment and ancillary services needed to connect to, access or otherwise use the Services, including, without limitation, modems, hardware, servers, software, operating systems, networking, web servers. Company shall also be responsible for maintaining the security of the Equipment, Company account, passwords (including but not limited to administrative and user passwords) and files, and for all uses of Company account or the Equipment with or without Company&apos;s knowledge or consent.
        <br/><br/>
        5.13 Usage Restrictions Customer shall not (a) make any Service or Content available to anyone other than Users, or use any Service or Content for the benefit of, anyone other than Customer, unless expressly stated otherwise in an Order Form, (i) copy or republish the Service (b) sell, resell, license, sublicense, distribute, make available, rent or lease the Service or Content, (ii) use or access the Service to provide service bureau, time-sharing or other computer hosting services to third parties, (c) use Service to store or transmit infringing, or otherwise unlawful or tortious material, or to store or transmit material in violation of third-party privacy rights, (d) use the Service to store or transmit Malicious Code, (e) interfere with or disrupt the integrity or performance of the Service or third-party data contained therein, (f) attempt to gain unauthorized access to the Service or Content or its related systems or networks, (g) permit direct or indirect access to or use of the Service or Content in a way that circumvents a contractual usage limit, or to access or use any of Our intellectual property except as permitted under this Agreement, an Order Form, or the Documentation, (h) modify, copy, or create derivative works based on a Service or any part, feature, function or user interface thereof, v) remove, modify or obscure any copyright, trademark or other proprietary notices contained in the software used to provide the Service or in the Documentation, (i) copy Content except as permitted herein or in an Order Form or the Documentation, (j) frame or mirror any part of the Service or Content, other than framing on Customer own intranets or otherwise for Customer own internal business purposes or as permitted in the Documentation, or (vi) reverse engineer, decompile, disassemble, or otherwise attempt to derive the source code of the Software used to provide the Service, except and only to the extent such activity is expressly permitted by applicable law, and not to access it to (1) build a competitive product or service, (2) build a product or service using similar ideas, features, functions or graphics of the Service, (3) copy any ideas, features, functions or graphics of the Service or (4) determine whether the Services are within the scope of any patent. Any use of the Services in breach of this Agreement, Documentation or Order Forms, by Customer or it&apos;s Users that in Apptino&apos;s judgment threatens the security, integrity or availability of Service, may result in Apptino immediate suspension of the Service, however, Apptino will use commercially reasonable efforts under the circumstances to provide Customer with notice and an opportunity to remedy such violation or threat prior to such suspension. (f) publicly disseminate information regarding the performance of the Apptino Product; or (g) access the Apptino Product if Customer is a direct competitor of Apptino, except with Apptino&apos;s prior written consent.
        </p>
        <h3 className={styles.legalHeading}>6.OWNERSHIP</h3>
        <p className={styles.legalPassage}>6.1 Apptino Service This is a subscription agreement for access to and use of the Service. Customer acknowledges that it is obtaining only a limited right to the Service and that irrespective of any use of the words “purchase”, “sale” or like terms in this Agreement no ownership rights are being conveyed to Customer under this Agreement. Customer agrees that Apptino retain all right, title and interest (including all patent, copyright, trademark, trade secret and other intellectual property rights) in and to the Service, Documentation, Professional Services deliverables and any and all related and underlying technology / services and documentation; and any derivative works, modifications or improvements of any of the foregoing, including as may incorporate Feedback Except as expressly set forth in this Agreement, no rights in any Service are granted to Customer. Further, Customer acknowledges that the Service is offered as an online, hosted solution and that Customer has no right to obtain a copy of the Service. Company further acknowledges that Apptino retains the right to use the foregoing for any purpose in Apptino&apos;s sole discretion.<br/><br/>
        6.2 Feedback Company may provide Apptino with feedback, comments and recommendations regarding the functionality and performance of the Service, including, without limitation, identifying potential errors and improvements (collectively, the “Feedback”). Apptino shall have the unrestricted right to use the Feedback provided by Customer to Apptino in connection with the Service or this Agreement at its sole discretion, including to improve or enhance the Apptino Service and other Apptino Services, and, accordingly, Apptino shall have a non-exclusive, perpetual, irrevocable, royalty-free, worldwide right and license to use, reproduce, disclose, sublicense, distribute, modify, and otherwise exploit such Feedback without restriction.</p>
        <h3 className={styles.legalHeading}>7.CONFIDENTIALITY</h3>
        <p className={styles.legalPassage}>7.1 Confidentiality Each Party hereby acknowledges that during the performance of this Agreement it may learn, receive or otherwise have access to Confidential Information (as defined herein) of the other Party. Each party understands that the other party has disclosed or may disclose business, technical or financial information relating to the other Party&apos;s business (hereinafter referred to as “Proprietary Information” of the other Party).  Proprietary Information of Apptino includes non-public information regarding the features, functionality, and performance of the Service.  Proprietary Information of Customer includes non-public data provided by Customer to Apptino to enable the provision of the Service (“Customer Data”)
        <br/>
        During the term of this Agreement, each party shall treat as confidential all Confidential Information of the other party, shall not use such Confidential Information except to exercise its rights and perform its obligations under this SaaS Agreement, and shall not disclose such Confidential Information to any third party. Without limiting the foregoing, each party shall use at least the same degree of care, but not less than a reasonable degree of care, it uses to prevent the disclosure of its own confidential information to prevent the disclosure of Confidential Information of the other party. Each party shall promptly notify the other party of any actual or suspected misuse or unauthorized disclosure of the other party&apos;s Confidential Information. Neither party shall reverse engineer, disassemble or decompile any prototypes, software or other tangible objects which embody the other party&apos;s Confidential Information and which are provided to the party hereunder. Each party may disclose Confidential Information of the other party on a need-to-know basis to its subcontractors who are subject to confidentiality agreements requiring them to maintain such information in confidence and use it only to facilitate the performance of their services on behalf of the receiving party.
        <br/>
        7.2 Exceptions Confidential Information excludes information that: (a) is known publicly at the time of the disclosure or becomes known publicly after disclosure through no fault of the receiving party, (b) is known to the receiving party, without restriction, at the time of disclosure or becomes known to the receiving party, without restriction, from a source other than the disclosing party not bound by confidentiality obligations to the disclosing party, or (c) is independently developed by the receiving party without use of the Confidential Information as demonstrated by the written records of the receiving party. The receiving party may disclose Confidential Information of the other party to the extent such disclosure is required by law or order of a court or other governmental authority, provided that the receiving party shall use reasonable efforts to promptly notify the other party prior to such disclosure to enable the disclosing party to seek a protective order or otherwise prevent or restrict such disclosure. Each party may disclose the existence of this SaaS Agreement and the relationship of the parties, but agrees that the specific terms of this SaaS Agreement will be treated as Confidential Information; provided, however, that each party may disclose the terms of this SaaS Agreement to those with a need to know and under a duty of confidentiality such as accountants, lawyers, bankers, and investors.
        <br/>
        7.3 Publicity Each Party grants the other Party the limited right to use its name and logo to identify it as a customer or service provider or other marketing materials, as applicable. Neither Party shall make any other use of the other Party’s name, or disclose the terms of this Agreement, without the other Party&apos;s written consent.
        </p>
        <h3 className={styles.legalHeading}>8.TERM AND TERMINATION</h3>
        <p className={styles.legalPassage}>8.1 Term This Agreement is effective as of the Order Form Effective Date and is for the Initial Subscription Period as specified in the Order Form. The extent of each subscription period shall be as specified in the applicable Order Form. Except as otherwise specified in an Order Form, subscriptions will automatically renew for additional periods equal to the expiring subscription period or one year (whichever is shorter), unless either party gives the other notice of non-renewal at least 30 days before the end of the relevant subscription term. Notwithstanding anything to the contrary, any renewal in which subscription volume for any Service has decreased from the prior subscription will result in re-pricing at renewal without regard to the prior period&apos;s pricing.<br/><br/>
        8.2 Termination for Convenience. Customer may terminate any Order Form at any time, for any reason or no reason upon thirty (30) days&apos; written notice to Apptino.<br/><br/>
        8.3 Termination for Cause. Either Party may, at its option, terminate this Agreement, or as applicable, an individual Order Form in the event of, (i) a material breach of this agreement. Such termination may be effected only through a written notice to the breaching Party, specifically identifying the breach or breaches on which such notice of termination is based. The breaching Party will have a right to cure such breach or breaches within thirty (30) days of receipt of such notice, and this Agreement, or the applicable Order Form. will terminate in the event that such a cure is not made within such thirty (30)-day period, (ii) ceases operation without a successor; or (c) seeks protection under any bankruptcy, receivership, trust deed, creditors&apos; arrangement, composition, or comparable proceeding, or if any such proceeding is instituted against that party (and not dismissed within sixty (60) days thereafter).
        <br/><br/>
        8.4 Effect of Termination (a) In either case, upon termination of this SaaS Agreement, Apptino shall immediately cease providing the Service and all usage rights granted under this SaaS Agreement shall terminate. Apptino will have no obligation to refund any prepaid subscription price covering the remainder of the term of all Order Forms after the effective date of termination.
        <br/><br/>
        Customer acknowledges that the following termination it shall have no further access to any Customer Data input into the Service.
        <br/>
        8.5 Suspension for Non-Payment Apptino reserves the right to suspend delivery of the Service if Customer fails to timely pay any undisputed amounts due to Apptino under this SaaS Agreement, but only after Apptino notifies Customer of such failure and such failure continues for fifteen (15) days.
        <br/><br/>
        8.6 Suspension for Ongoing Harm Apptino reserves the right to suspend delivery of the Service if Apptino reasonably concludes that Customer use of the Service is causing immediate and ongoing harm to Apptino or others. In the extraordinary case that Apptino must suspend delivery of the Service, Apptino shall immediately notify Customer of the suspension and the parties shall diligently attempt to resolve the issue In either case, Customer agrees that Apptino shall not be liable to Customer or to any third party for any liabilities, claims or expenses arising from or relating to suspension of the Service.
        <br/><br/>
        8.7 Customer Data Portability and Deletion Upon request by customer made within 7 business days after the effective date of termination or expiration of this Agreement, Apptino will make customer Data available for export or download as provided in the Documentation. Customer shall have read-only access to the Service to export and retrieve its Data within thirty (30) days after the effective date of termination. Thirty (30) days after the effective date of termination, Apptino shall have no obligation to maintain or provide any Customer Data. Except when Customer Data has been removed in accordance with the Agreement or exported by Customer, upon termination of the Agreement, Apptino shall, using industry standard technology and to the extent possible, permanently and irrevocably remove, delete, purge or overwrite all data still remaining on the servers used to host the Service, including, but not limited to, Customer Data, unless and to the extent applicable laws and regulations require further retention of such data, during which case, Customer will notify Apptino in writing.
        </p>
        <h3 className={styles.legalHeading}>9.REPRESENTATION, WARRANTY, EXCLUSIONS, AND DISCLAIMER</h3>
        <p className={styles.legalPassage}>9.1 Reciprocal Representations Each Party hereby represents that it is duly authorized to enter into this Agreement and to make the commitments and grant the rights set forth in this Agreement.
        <br/><br/>
        9.2 Apptino Warranties Apptino represents and warrants that it would use reasonable efforts consistent with prevailing industry standards to maintain the Service in a manner which minimizes errors and interruptions in the Service and shall perform the Service in a professional and workmanlike manner.  Service may be temporarily unavailable for scheduled maintenance or for unscheduled emergency maintenance, either by Apptino or by third-party providers, or because of other causes beyond Apptino&apos;s reasonable control, but Apptino shall use reasonable efforts to provide advance notice in writing of any scheduled service disruption. 
        <br/><br/>
        Apptino warrants that during an applicable subscription period (a) this Agreement, the Order Forms will accurately describe the applicable administrative, physical, and technical safeguards for protection of the security, confidentiality, and integrity of Customer Data, (b) Apptino will not materially decrease the overall security of the Service, (c) Apptino will not materially decrease the overall functionality of the Service.
        <br/>
        APPTINO DOESNT WARRANT OR GUARANTEE THAT THE OPERATION OF THE SUBSCRIPTION SERVICE WILL BE UNINTERRUPTED, VIRUS-FREE OR ERROR-FREE or that Apptino will correct all service errors;, nor does it make any warranty as to the results that may be obtained from use of the Service NOR SHALL APPTINO BE LIABLE FOR UNAUTHORIZED ALTERATION, THEFT OR DESTRUCTION OF CUSTOMER&apos;S OR ANY USER&apos;S DATA, FILES, OR PROGRAMS.
        <br/>
        9.3 Exclusions CUSTOMER ACKNOWLEDGES THAT Apptino DOES NOT CONTROL THE TRANSFER OF DATA OVER COMMUNICATIONS FACILITIES, INCLUDING THE INTERNET, AND THAT THE  SERVICE MAY BE SUBJECT TO LIMITATIONS, DELAYS, AND OTHER PROBLEMS INHERENT IN THE USE OF SUCH COMMUNICATIONS FACILITIES. THIS SECTION SETS FORTH THE SOLE AND EXCLUSIVE WARRANTY GIVEN BY Apptino (EXPRESS OR IMPLIED) WITH RESPECT TO THE SUBJECT MATTER OF THIS AGREEMENT.
        <br/><br/>
        9.4 Disclaimer EXCEPT AS EXPRESSLY SET FORTH IN THIS SECTION, THE SERVICE is PROVIDED “AS IS” AND APPTINO DISCLAIMS any and ALL other promises, representations, and WARRANTIES, whether EXPRESS OR IMPLIED, STATUTORY OR OTHERWISE INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT, SYSTEM INTEGRATION AND/OR DATA ACCURACY TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW.
        </p>
        <h3 className={styles.legalHeading}>10.INDEMNITY</h3>
        <p className={styles.legalPassage}>10.1 Indemnification by Apptino Apptino shall indemnify, defend and hold Customer harmless from liability to third parties resulting from infringement by the Service of any patent or any copyright or misappropriation of any trade secret, provided Apptino is promptly notified of any and all threats, claims and proceedings related thereto and given reasonable assistance and the opportunity to assume sole control over defense and settlement; Apptino will not be responsible for any settlement it does not approve in writing.  The foregoing obligations do not apply with respect to portions or components of the Service (i) not supplied by Apptino, (ii) made in whole or in part in accordance with Customer specifications, (iii) a claim against Customer arises from Service under an Order Form for which there is no charge, (iv) combined with other products, processes or materials where the alleged infringement relates to such combination, (v) where Customer continues allegedly infringing activity after being notified thereof or after being informed of modifications that would have avoided the alleged infringement,  (vi) where Customer&apos;s use of the Service is not strictly in accordance with this Agreement, (vii) a Claim against Customer is based on traditional online commerce functionality that is or was in general use in the industry, (viii) if the alleged infringement is a result of use of the Service in combination with any third party product, (ix) if the applicable fees due for the specific Service have not been paid by Customer to Apptino, (x) if the alleged infringement would be avoided or otherwise eliminated by the use of an Apptino published update for the software used in the Service.
        <br/><br/>
        If, due to a claim of infringement, the Service is held by a court of competent jurisdiction to be or are believed by Apptino to be infringing, Apptino may, at its discretion and expense (a) replace or modify the Service to be non-infringing such that the modification or replacement doesn&apos;t contain substantially similar features and functionality, (b) if the foregoing is not commercially practicable, terminate this Agreement and Customer&apos;s rights hereunder upon 30 days&apos; written notice and provide Company a refund of any prepaid, unused fees for the Service covering the remainder of the period of the terminated subscriptions.
        <br/><br/>
        10.2 Indemnification by Customer If a third party makes a claim against Apptino that the Customer Content infringes any patent, copyright or trademark, or misappropriates any trade secret, Customer shall indemnify, defend and hold harmless Apptino and its directors, officers and employees against the claim at Customer&apos;s expense and Customer shall pay all losses, damages and out-of-pocket expenses finally awarded against such parties or agreed to in a written settlement agreement signed by Customer, to the extent arising from the claim.
        <br/><br/>
        Customer shall indemnify, defend and hold harmless Apptino against any claim that any data, materials, items or information supplied to Apptino under the Agreement infringes any patent, copyright or trademark within the jurisdictions where Apptino is provided with such information.
        </p>
        <h3 className={styles.legalHeading}>11.LIMITATION OF LIABILITY</h3>
        <p className={styles.legalPassage}>NOTWITHSTANDING ANYTHING TO THE CONTRARY, APPTINO AND ITS SUPPLIERS (INCLUDING BUT NOT LIMITED TO ALL EQUIPMENT AND TECHNOLOGY SUPPLIERS), OFFICERS, AFFILIATES, REPRESENTATIVES, CONTRACTORS AND EMPLOYEES SHALL NOT BE RESPONSIBLE OR LIABLE WITH RESPECT TO ANY SUBJECT MATTER OF THIS AGREEMENT OR TERMS AND CONDITIONS RELATED THERETO UNDER ANY CONTRACT, NEGLIGENCE, STRICT LIABILITY OR OTHER THEORY: (A) FOR ERROR OR INTERRUPTION OF USE OR FOR LOSS OR INACCURACY OR CORRUPTION OF DATA OR COST OF PROCUREMENT OF SUBSTITUTE GOODS, SERVICES OR TECHNOLOGY OR LOSS OF profits or revenues; (B) FOR ANY INDIRECT, EXEMPLARY, INCIDENTAL, SPECIAL OR CONSEQUENTIAL DAMAGES; (C) FOR ANY MATTER BEYOND APPTINO&apos;S REASONABLE CONTROL; OR (D) FOR ANY AMOUNTS THAT, TOGETHER WITH AMOUNTS ASSOCIATED WITH ALL OTHER CLAIMS, EXCEED THE PRICE PAID BY CUSTOMER TO APPTINO FOR THE SERVICES UNDER THIS AGREEMENT IN THE 12 MONTHS PRIOR TO THE ACT THAT GAVE RISE TO THE LIABILITY, IN EACH CASE, WHETHER OR NOT APPTINO HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
        </p>
        <h3 className={styles.legalHeading}>12.DISPUTE RESOLUTION</h3>
        <p className={styles.legalPassage}>12.1 Any dispute, controversy or claim arising out of the Agreement or the interpretation thereof (a “Dispute”) shall be resolved as provided in this Section. Prior to the initiation of formal dispute resolution procedures, the Parties shall first meet as often, and for such duration and as promptly as the Parties reasonably deem necessary to discuss the Dispute and negotiate in good faith in an effort to resolve the Dispute. If Customer and Apptino are unable to resolve the Dispute within thirty (30) days after the referral of the Dispute to them, then each Party will appoint one (1) senior executive who is not involved on a day-to-day basis with the subject matter of the Agreement and will negotiate the matter in good faith in an effort to resolve the Dispute without the necessity of any formal proceedings.<br/><br/>
        12.2 Formal proceedings for the resolution of a Dispute may not be commenced until the earlier of: (i) the good faith determination by the appointed senior executives that amicable resolution through continued negotiation of the matter does not appear likely; or (ii) thirty (30) days following the date that the Dispute was first referred to the appointed senior executives. The provisions of paragraphs (i) and (ii) will not be construed to prevent a Party from instituting formal proceedings to the extent necessary to avoid the expiration of any applicable limitations period or to pursue equitable rights or injunctive remedies deemed reasonably necessary to protect its interests.<br/>
        </p>
        <h3 className={styles.legalHeading}>13.MISCELLANEOUS</h3>
        <p className={styles.legalPassage}>If any provision of this Agreement is found to be unenforceable or invalid, that provision will be limited or eliminated to the minimum extent necessary so that this Agreement will otherwise remain in full force and effect and enforceable.
        <br/>
        This agreement will bind and inure to the benefit of each party&apos;s permitted successors and assigns. Neither party may assign this Agreement without the advance written consent of the other party, except that either party may assign this Agreement in connection with a merger, reorganization, acquisition or other transfer of all or substantially all of such party&apos;s assets or voting securities. Any attempt to transfer or assign this Agreement except as expressly authorized under this section will be null and void.
        <br/>
        This Agreement shall be governed by the laws of the State of Tamilnadu without regard to its conflict of law&apos;s provisions.
        <br/>
        No agency, partnership, joint venture, or employment is created as a result of this Agreement and Customer does not have any authority of any kind to bind Apptino in any respect whatsoever. In any action or proceeding to enforce rights under this Agreement, the prevailing party will be entitled to recover costs and attorneys&apos; fees.  All notices under this Agreement will be in writing and will be deemed to have been duly given when received, if personally delivered; when receipt is electronically confirmed, if transmitted by facsimile or e-mail; the day after it is sent, if sent for next day delivery by recognized overnight delivery service; and upon receipt, if sent by certified or registered mail, return receipt requested.
        <br/>
        This Agreement is the complete and exclusive statement of the mutual understanding of the parties and supersedes and cancels all previous written and oral agreements, communications and other understandings relating to the subject matter of this Agreement, and that all waivers and modifications must be in a writing signed by both parties, except as otherwise provided herein. Customer acknowledges that the Service is an online, subscription based one and that in order to provide improved customer experience, Apptino may make changes to the Service, and Apptino will update the applicable documentation accordingly. The terms described in the Security Policy, Cookies Policy, Privacy Policy may be updated from time to time upon reasonable notice to Customer to reflect process improvements or changing practices but any such modifications will not materially decrease Apptino&apos;s obligations as compared to those reflected in such terms as of the order form effective date.
        <br/>
        Neither party shall be liable for failure to perform obligations under this Agreement if the failure results from an act of God, the act of a national, international, state or local government authority, fire, explosion, accident, industrial dispute, or any other catastrophic or other similar event beyond such Party&apos;s reasonable control (collectively “Force Majeure”). If Apptino is affected by an event of Force Majeure, upon giving prompt notice to Customer, Apptino shall be excused from performance hereunder on a day-to-day basis to the extent of the prevention, restriction, and interference resulting from such Force Majeure.
        <br/>
        The parties shall work together in good faith to issue at least one mutually agreed upon press release within 90 days of the Effective Date, and Customer otherwise agrees to reasonably cooperate with Apptino to serve as a reference account upon request.
        </p>
    </div>

  )
}

export default MSA